# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QDialog
from PyQt5.QtGui import QFont, QCursor
import sys
import sqlite3
import classclient as cli
import qdarkstyle
import os


class Ui_LoginWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.resize(550, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutIn = QtWidgets.QVBoxLayout()
        self.verticalLayoutIn.setContentsMargins(50, 0, 50, 0)
        #self.formLayout = QtWidgets.QFormLayout()
        #self.formLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayoutIn.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayoutIn.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font.setPointSize(15)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutIn.addWidget(self.label_2)
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setFont(font)
        self.email.setObjectName("plainTextEdit")
        self.verticalLayoutIn.addWidget(self.email)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutIn.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setFont(font)
        self.password.setObjectName("plainTextEdit_3")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayoutIn.addWidget(self.password)
        self.verticalLayout.addLayout(self.verticalLayoutIn)
        self.gridLayout = QtWidgets.QGridLayout()
        #self.gridLayout.setContentsMargins(5, 0, 5, 50)
        self.gridLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.LogIn)
        font.setPointSize(15)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("padding: 12px")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        font.setPointSize(12)
        font.setBold(False)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.label4.mousePressEvent = self.signUp
        self.label4.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        
        self.verticalLayout.addWidget(self.label4)

##        self.username_inp = QtWidgets.QLineEdit(self.centralwidget)
##        self.username_inp.setGeometry(QtCore.QRect(210, 210, 221, 31))
##        self.username_inp.setObjectName("username_inp")
##        self.pass_inp = QtWidgets.QLineEdit(self.centralwidget)
##        self.pass_inp.setGeometry(QtCore.QRect(210, 300, 221, 31))
##        self.pass_inp.setObjectName("pass_inp")
##        self.pass_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def signUp(self, event):
        os.system('python register.py')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Application"))
        self.label.setText(_translate("MainWindow", "Login User"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label4.setText(_translate("MainWindow", "Create new account"))
        self.pushButton.setText(_translate("MainWindow", "Sign In"))
        
    def LogIn(self):
        Email = self.email.text()
        Password = self.password.text()
        checker = [Email, Password]
        print(Email,Password)

        if "" in checker:
            dlg = QDialog()
            dlg.setStyleSheet(dark_stylesheet)
            dlg.setWindowTitle("Error")
            dlg.resize(360, 100)
            contact = QLabel('\nEmpty Fields aren\'t accepted!', dlg)
            contact.setAlignment(QtCore.Qt.AlignCenter)
            contact.setFont(QFont("Arial Rounded MT Bold", 14))
            # contact.setStyleSheet("color: white")
            contact.move(10, 10)
            dlg.exec_()

        else:
            #fetchall
            conn = sqlite3.connect("chatapp.db")
            print("CONNECTED")
            cur = conn.cursor()
            print("CURSOR SET")
            cur.execute("SELECT * FROM USERS WHERE EMAIL = ? AND PASSWORD = ?",(Email,Password))
            print("QUERY EXECUTED")
            result=cur.fetchone()
            
            if not result:
                dlg = QDialog()
                #dlg.setStyleSheet(dark_stylesheet)
                dlg.setWindowTitle("Error")
                dlg.resize(240, 100)
                contact = QLabel('\nInvalid Credentials!', dlg)
                contact.setAlignment(QtCore.Qt.AlignCenter)
                contact.setFont(QFont("Arial Rounded MT Bold", 14))
                #contact.setStyleSheet("text-align: center")
                contact.move(10, 10)
                dlg.exec_()
            else:
                print('Login Succesfull')
                print(result[0])
                LoginWindow.close()
                user=cli.Client(username=result[0])
                user.connect()
                user.mainloop()
                
            conn.close()

login = QApplication(sys.argv)
dark_stylesheet = qdarkstyle.load_stylesheet_pyqt5()
login.setStyleSheet(dark_stylesheet)
login.setWindowIcon(QtGui.QIcon('chat-icon.png'))
LoginWindow = QMainWindow()
Ui = Ui_LoginWindow()
Ui.setupUi(LoginWindow)
LoginWindow.show()
login.exec()
