1# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys
import login
import register

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 90, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(240, 230, 121, 41))
        self.loginButton.clicked.connect(self.openLoginWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.registerUser = QtWidgets.QPushButton(self.centralwidget)
        self.registerUser.setGeometry(QtCore.QRect(240, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerUser.setFont(font)
        self.registerUser.setObjectName("registerUser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Chat Application"))
        self.loginButton.setText(_translate("MainWindow", "Login User"))
        self.registerUser.setText(_translate("MainWindow", "Register User"))
    def openLoginWindow(self):
        login = QApplication(sys.argv)
        LoginWindow = QMainWindow()
        Ui = Ui_LoginWindow()
        Ui.setupUi(LoginWindow)
        LoginWindow.show()
        login.exec()
    def openRegisterWindow(self):
        register = QApplication(sys.argv)
        MainWindow = QMainWindow()
        Ui = Ui_MainWindow()
        Ui.setupUi(MainWindow)
        MainWindow.show()
        register.exec()
                
app = QApplication(sys.argv)
MainWindow = QMainWindow()
Ui = Ui_MainWindow()
Ui.setupUi(MainWindow)
MainWindow.show()
app.exec()
