# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# import required modules
import socket
import threading

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys
HOST = '127.0.0.1'
PORT = 1234
class Ui_ClientWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.Message = QtWidgets.QLabel(self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(110, 10, 401, 16))
        self.Message.setObjectName("Message")
        self.text_send = QtWidgets.QLineEdit(self.centralwidget)
        self.text_send.setGeometry(QtCore.QRect(10, 520, 421, 31))
        self.text_send.setObjectName("text_send")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(440, 520, 71, 31))
        self.sendButton.setObjectName("sendButton")
        self.sendButton.clicked.connect(self.sendMsg(self.text_send.text()))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name.setText(_translate("MainWindow", "Person Name"))
        self.Message.setText(_translate("MainWindow", "ABC test msg"))
        self.sendButton.setText(_translate("MainWindow", "SEND"))
    def sendMsg(self,message):
        pass
client = QApplication(sys.argv)
ClientWindow = QMainWindow()
Ui = Ui_ClientWindow()
Ui.setupUi(ClientWindow)
ClientWindow.show()
client.exec()
